/**
 * AES-256-GCM symmetric encryption helper (Phase H1).
 *
 * Used for at-rest encryption of secrets stored in PostgreSQL:
 *   - servers.coolify_api_token_encrypted
 *   - servers.ssh_private_key_encrypted
 *   - operator_users.two_factor_secret
 *   - operator_users.two_factor_backup_codes (per element)
 *
 * Master key is read from MASTER_KEY env var as 64 hex chars (32 bytes / 256
 * bits). Generate with `openssl rand -hex 32`.
 *
 * Wire format (single-line, colon-separated hex):
 *   "<iv-hex>:<authTag-hex>:<ciphertext-hex>"
 *
 * Why this format:
 *   - Round-trippable through PostgreSQL `text` columns (no binary escaping).
 *   - Self-contained: IV + auth tag + ciphertext live together so a single
 *     column read yields everything needed for decrypt.
 *   - Fail-loud: malformed input throws before reaching the cipher.
 *
 * Authentication: AES-GCM provides built-in integrity. Tampering with any
 * byte (IV, tag, or ciphertext) causes `decipher.final()` to throw.
 *
 * --- ROUNDTRIP TEST FIXTURES (paste into a Vitest spec under tests/) ---
 *
 *   import { encrypt, decrypt } from '@/lib/crypto/aes-gcm';
 *
 *   beforeAll(() => {
 *     // 64 hex chars (32 bytes). Deterministic for tests; production uses
 *     // a random key generated by `openssl rand -hex 32`.
 *     process.env.MASTER_KEY =
 *       '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef';
 *   });
 *
 *   test('roundtrip: simple ASCII', () => {
 *     const blob = encrypt('hello world');
 *     expect(blob.split(':')).toHaveLength(3);
 *     expect(decrypt(blob)).toBe('hello world');
 *   });
 *
 *   test('roundtrip: TOTP-shaped secret', () => {
 *     const secret = 'JBSWY3DPEHPK3PXP';
 *     expect(decrypt(encrypt(secret))).toBe(secret);
 *   });
 *
 *   test('roundtrip: SSH private key (multiline PEM)', () => {
 *     const pem =
 *       '-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAA...\n-----END OPENSSH PRIVATE KEY-----\n';
 *     expect(decrypt(encrypt(pem))).toBe(pem);
 *   });
 *
 *   test('non-determinism: same plaintext produces different blobs', () => {
 *     const a = encrypt('same input');
 *     const b = encrypt('same input');
 *     expect(a).not.toBe(b);            // random IV per call
 *     expect(decrypt(a)).toBe(decrypt(b));
 *   });
 *
 *   test('tamper detection: flipped ciphertext byte throws', () => {
 *     const blob = encrypt('integrity check');
 *     const [iv, tag, ct] = blob.split(':');
 *     const flipped = ct.startsWith('0') ? '1' + ct.slice(1) : '0' + ct.slice(1);
 *     expect(() => decrypt(`${iv}:${tag}:${flipped}`)).toThrow();
 *   });
 *
 *   test('rejects malformed blob', () => {
 *     expect(() => decrypt('not-a-blob')).toThrow(/Invalid encrypted blob/);
 *     expect(() => decrypt('only:two')).toThrow(/Invalid encrypted blob/);
 *   });
 *
 *   test('rejects bad MASTER_KEY', () => {
 *     const saved = process.env.MASTER_KEY;
 *     process.env.MASTER_KEY = 'too-short';
 *     expect(() => encrypt('x')).toThrow(/MASTER_KEY/);
 *     process.env.MASTER_KEY = saved;
 *   });
 */

import crypto from 'node:crypto';

const ALGO = 'aes-256-gcm';
const IV_LEN = 12; // 96 bits — NIST-recommended GCM nonce size
const KEY_LEN = 32; // 256 bits
const KEY_HEX_LEN = KEY_LEN * 2; // 64 hex chars

function getKey(): Buffer {
  const hex = process.env['MASTER_KEY'];
  if (!hex || hex.length !== KEY_HEX_LEN) {
    throw new Error(
      `MASTER_KEY env var must be ${KEY_HEX_LEN} hex chars (${KEY_LEN} bytes). ` +
        `Generate with: openssl rand -hex ${KEY_LEN}`,
    );
  }
  // Defence-in-depth: ensure it's actually hex (not e.g. base64 of same len).
  if (!/^[0-9a-fA-F]+$/.test(hex)) {
    throw new Error('MASTER_KEY env var must be valid hex');
  }
  return Buffer.from(hex, 'hex');
}

/**
 * Encrypt a UTF-8 string. Returns an opaque blob suitable for storage in a
 * `text` column. Each call generates a fresh random IV — calling twice with
 * the same plaintext yields different blobs (this is required for GCM
 * security; reusing an IV with the same key is catastrophic).
 */
export function encrypt(plaintext: string): string {
  const iv = crypto.randomBytes(IV_LEN);
  const cipher = crypto.createCipheriv(ALGO, getKey(), iv);
  const encrypted = Buffer.concat([
    cipher.update(plaintext, 'utf8'),
    cipher.final(),
  ]);
  const authTag = cipher.getAuthTag();
  return `${iv.toString('hex')}:${authTag.toString('hex')}:${encrypted.toString('hex')}`;
}

/**
 * Decrypt a blob produced by `encrypt()`. Throws if:
 *   - `blob` is not in the expected `iv:tag:ct` shape
 *   - the IV/tag/ciphertext are not valid hex
 *   - the auth tag does not validate (tampering or wrong key)
 */
export function decrypt(blob: string): string {
  const parts = blob.split(':');
  if (parts.length !== 3) {
    throw new Error('Invalid encrypted blob format (expected iv:tag:ct)');
  }
  const [ivHex, tagHex, ctHex] = parts;
  if (!ivHex || !tagHex || !ctHex) {
    throw new Error('Invalid encrypted blob format (empty segment)');
  }
  const iv = Buffer.from(ivHex, 'hex');
  const tag = Buffer.from(tagHex, 'hex');
  const ct = Buffer.from(ctHex, 'hex');
  if (iv.length !== IV_LEN) {
    throw new Error(`Invalid IV length (expected ${IV_LEN}, got ${iv.length})`);
  }
  if (tag.length !== 16) {
    throw new Error(`Invalid auth tag length (expected 16, got ${tag.length})`);
  }
  const decipher = crypto.createDecipheriv(ALGO, getKey(), iv);
  decipher.setAuthTag(tag);
  const decrypted = Buffer.concat([decipher.update(ct), decipher.final()]);
  return decrypted.toString('utf8');
}

/**
 * Convenience helper for nullable columns: pass-through `null`/`undefined`,
 * encrypt non-empty strings. Use when writing rows where the secret is
 * optional (e.g. `coolify_api_token_encrypted`).
 */
export function encryptNullable(plaintext: string | null | undefined): string | null {
  if (plaintext == null || plaintext === '') return null;
  return encrypt(plaintext);
}

/**
 * Mirror of `encryptNullable` for reads.
 */
export function decryptNullable(blob: string | null | undefined): string | null {
  if (blob == null || blob === '') return null;
  return decrypt(blob);
}
